/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cards;

/**
 *
 * @author rdpalmer
 */
public class Card extends javax.swing.JPanel {
    
    CardHand hand;
    String name;
    int ind;
    CardsUI cardsUI;
    int playerNum;
    int opponentNum;
   
    public Card(String name, int playerNum, CardHand hand, int ind, CardsUI cardsUI) {
        initComponents();

        this.hand = hand;
        this.name = name;
        this.cardsUI = cardsUI;
        this.playerNum = playerNum;
        
        opponentNum = (playerNum==1) ? 2 : 1;
        
        cardName.setText(name);
        setNum(ind);
    }
    
    public void setNum(int num){
        ind = num;
        description.setText("Position "+ind);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardName = new javax.swing.JLabel();
        attack = new javax.swing.JButton();
        targetList = new javax.swing.JComboBox();
        description = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(100, 200));
        setSize(new java.awt.Dimension(100, 200));

        cardName.setText("This is a Card");

        attack.setText("Go");
        attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackActionPerformed(evt);
            }
        });

        targetList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Attack 1", "Attack 2", "Attack 3", "Attack 4", "Attack 5", "Attack 6", "Attack 7" }));

        description.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardName)
                    .addComponent(targetList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attack)
                    .addComponent(description))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void attackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackActionPerformed
        cardsUI.attackCard(opponentNum, targetList.getSelectedIndex());
    }//GEN-LAST:event_attackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attack;
    private javax.swing.JLabel cardName;
    private javax.swing.JLabel description;
    private javax.swing.JComboBox targetList;
    // End of variables declaration//GEN-END:variables
}
